#!/usr/bin/env python
#
# dsbuild

import jinja2
import os
import subprocess
import sys
import tempfile
import yaml

def load_params(filename):
	with open (filename, "r") as myfile:
		params = yaml.safe_load(myfile)

	return params

def load_template(filename, params):
	templateLoader = jinja2.FileSystemLoader( searchpath="/" )
	templateEnv = jinja2.Environment( loader=templateLoader )
	template = templateEnv.get_template( os.path.realpath(filename) )

	return template.render(params)

def main():
	args = {
		"params": "dsbuild.yml",
		"src": "dsbuild"
	}
	params = load_params(args.params)
	outputText = load_template(args.src, params)
	with tempfile.NamedTemporaryFile() as tmpfile:
		# write out the code to execute
		tmpfile.write(outputText)
		# execute the code
		retval = subprocess.call(["bash", "-c", tmpfile.name])

	sys.exit(retval)

main()